(define-library (hop pass cfa)
  ;;; Pass 3.5: CFA Normalization
  ;;; Pass 3.6: 0CFA Analysis and Known-Call Rewriting
  (export normalize-for-cfa
          run-0cfa
          rewrite-known-calls)
  (import (scheme base)
          (scheme cxr)
          (srfi 69)
          (hop utils))
  (begin

(define (cfa-simple-expr? expr)
  (or (symbol? expr)
      (literal-expr? expr)
      (and (pair? expr) (memq (car expr) '(local closure global)))))

(define (wrap-let-bindings bindings body)
  (let loop ((rest (reverse bindings)) (result body))
    (if (null? rest)
        result
        `(let (,(car rest)) ,(loop (cdr rest) result)))))

(define (normalize-for-cfa expr)
  (define temp-counter 0)
  (define proc-counter 0)

  (define (fresh-cfa-temp)
    (set! temp-counter (+ temp-counter 1))
    (string->symbol (string-append "cfa.tmp." (number->string temp-counter))))

  (define (fresh-cfa-proc)
    (set! proc-counter (+ proc-counter 1))
    (string->symbol (string-append "cfa.proc." (number->string proc-counter))))

  (define (normalize-simple expr)
    (let ((normalized (normalize expr)))
      (if (cfa-simple-expr? normalized)
          (values '() normalized)
          (let ((tmp (fresh-cfa-temp)))
            (values (list (list tmp normalized)) tmp)))))

  (define (normalize-simple-list exprs)
    (let loop ((rest exprs) (bindings '()) (result '()))
      (if (null? rest)
          (values bindings (reverse result))
          (let-values (((new-bindings simple-expr)
                        (normalize-simple (car rest))))
            (loop (cdr rest)
                  (append bindings new-bindings)
                  (cons simple-expr result))))))

  (define (normalize-sequence exprs)
    (map normalize exprs))

  (define (normalize expr)
    (cond
     ((or (symbol? expr) (literal-expr? expr)) expr)
     ((pair? expr)
      (case (car expr)
        ((begin)
         `(begin ,@(normalize-sequence (cdr expr))))
        ((primop)
         `(primop ,(cadr expr)
                  ,@(normalize-sequence (cddr expr))))
        ((if)
         `(if ,(normalize (cadr expr))
              ,(normalize (caddr expr))
              ,(normalize (cadddr expr))))
        ((let)
         (let* ((bindings (map (lambda (binding)
                                 (list (car binding)
                                       (normalize (cadr binding))))
                               (cadr expr)))
                (body-exprs (normalize-sequence (cddr expr))))
           `(let ,bindings ,@body-exprs)))
        ((lambda)
         `(lambda ,(cadr expr) ,@(normalize-sequence (cddr expr))))
        ((make-closure)
         (let* ((lambda-expr (cadr expr))
                (captures (cddr expr)))
           (let-values (((capture-bindings simple-captures)
                         (normalize-simple-list captures)))
             (let ((proc-name (fresh-cfa-proc)))
               (wrap-let-bindings
                capture-bindings
                `(make-closure ,proc-name
                               ,(normalize lambda-expr)
                               ,@simple-captures))))))
        ((closure-call)
         (let-values (((op-bindings simple-op)
                       (normalize-simple (cadr expr)))
                      ((arg-bindings simple-args)
                       (normalize-simple-list (cddr expr))))
           (wrap-let-bindings
            (append op-bindings arg-bindings)
            `(closure-call ,simple-op ,@simple-args))))
        ((self-tail-call)
         (let-values (((arg-bindings simple-args)
                       (normalize-simple-list (cdr expr))))
           (wrap-let-bindings arg-bindings `(self-tail-call ,@simple-args))))
        ((group-tail-call)
         (let-values (((arg-bindings simple-args)
                       (normalize-simple-list (cddr expr))))
           (wrap-let-bindings
            arg-bindings
            `(group-tail-call ,(cadr expr) ,@simple-args))))
        ((group-closures)
         `(group-closures
           ,(map (lambda (member)
                   (list (car member)
                         (cadr member)
                         (caddr member)
                         (normalize (cadddr member))))
                 (cadr expr))
           ,(map (lambda (capture-spec)
                   (list (car capture-spec)
                         (normalize (cadr capture-spec))))
                 (caddr expr))))
        ((cons)
         (error "cons in normalize-for-cfa: should have been canonicalized" expr))
        ((make-vector)
         (error "make-vector in normalize-for-cfa: should have been canonicalized" expr))
        ((vector-length)
         (error "vector-length in normalize-for-cfa: should have been canonicalized" expr))
        ((vector-ref)
         (error "vector-ref in normalize-for-cfa: should have been canonicalized" expr))
        ((vector-set!)
         (error "vector-set! in normalize-for-cfa: should have been canonicalized" expr))
        ((set-box!)
         `(set-box! ,(normalize (cadr expr)) ,(normalize (caddr expr))))
        ((box unbox)
         `(,(car expr) ,(normalize (cadr expr))))
        ((set-global!)
         `(set-global! ,(cadr expr) ,(normalize (caddr expr))))
        ((local closure global)
         expr)
        (else
         (error "Unknown expression in CFA normalization" (car expr)))))
     (else
      (error "Invalid expression in CFA normalization" expr))))

  (normalize expr))

(define (run-0cfa expr)
  (define procedures (make-hash-table))
  (define var-flow (make-hash-table))
  (define box-flow (make-hash-table))
  (define global-flow (make-hash-table))
  (define proc-results (make-hash-table))
  (define changed #f)

  (define (table-keys table)
    (hash-table-keys table))

  (define (flow-ref table key)
    (let ((value (hash-table-ref/default table key #f)))
      (if value value '())))

  (define (add-flow! table key values)
    (if (or (not key) (null? values))
        #f
        (let* ((current (flow-ref table key))
               (updated (dedupe-symbols (append current values))))
          (if (set-equal? current updated)
              #f
              (begin
                (hash-table-set! table key updated)
                (set! changed #t)
                #t)))))

  (define (repr-name expr)
    (cond
     ((symbol? expr) expr)
     ((and (pair? expr) (memq (car expr) '(local closure))) (cadr expr))
     (else #f)))

  (define (box-key expr)
    (repr-name expr))

  (define (collect-procedures expr)
    (cond
     ((or (symbol? expr) (literal-expr? expr)) 'done)
     ((pair? expr)
      (case (car expr)
        ((begin)
         (for-each collect-procedures (cdr expr)))
        ((primop cons set-box!)
         (for-each collect-procedures (cdr expr)))
        ((if)
         (collect-procedures (cadr expr))
         (collect-procedures (caddr expr))
         (collect-procedures (cadddr expr)))
        ((let)
         (collect-procedures (cadr (caadr expr)))
         (for-each collect-procedures (cddr expr)))
        ((lambda)
         (for-each collect-procedures (cddr expr)))
        ((make-closure)
         (let ((proc-name (cadr expr))
               (lambda-expr (caddr expr))
               (captures (cdddr expr)))
           (hash-table-set! procedures
                            proc-name
                            (list (length captures)
                                  (cadr lambda-expr)
                                  (body->expr (cddr lambda-expr))))
           (collect-procedures (body->expr (cddr lambda-expr)))
           (for-each collect-procedures captures)))
        ((closure-call known-call self-tail-call)
         (for-each collect-procedures (cdr expr)))
        ((group-tail-call)
         (for-each collect-procedures (cddr expr)))
        ((group-closures)
         (for-each (lambda (member)
                     (collect-procedures (cadddr member)))
                   (cadr expr))
         (for-each (lambda (capture-spec)
                     (collect-procedures (cadr capture-spec)))
                   (caddr expr)))
        ((box unbox)
         (collect-procedures (cadr expr)))
        ((set-global!)
         (collect-procedures (caddr expr)))
        ((local closure global) 'done)
        (else
         (error "Unknown expression while collecting CFA procedures" (car expr)))))
     (else
      (error "Invalid expression while collecting CFA procedures" expr))))

  (collect-procedures expr)

  (define (analyze-expr expr current-proc)
    (cond
     ((literal-expr? expr) '())
     ((symbol? expr) (flow-ref var-flow expr))
     ((pair? expr)
      (case (car expr)
        ((local closure)
         (flow-ref var-flow (cadr expr)))
        ((global)
         (flow-ref global-flow (cadr expr)))
        ((begin)
         (let loop ((rest (cdr expr)) (last '()))
           (if (null? rest)
               last
               (loop (cdr rest)
                     (analyze-expr (car rest) current-proc)))))
        ((primop)
         (begin
           (for-each (lambda (subexpr)
                       (analyze-expr subexpr current-proc))
                     (cdr expr))
           '()))
        ((if)
         (begin
           (analyze-expr (cadr expr) current-proc)
           (set-union (analyze-expr (caddr expr) current-proc)
                      (analyze-expr (cadddr expr) current-proc))))
        ((let)
         (for-each (lambda (binding)
                     (let ((var (car binding))
                           (value-set (analyze-expr (cadr binding) current-proc)))
                       (add-flow! var-flow var value-set)))
                   (cadr expr))
         (analyze-expr (body->expr (cddr expr)) current-proc))
        ((make-closure)
         (let* ((proc-name (cadr expr))
                (meta (hash-table-ref/default procedures proc-name #f))
                (capture-count (car meta))
                (params (cadr meta))
                (captures (cdddr expr))
                (env-params
                 (let loop ((rest params) (remaining capture-count) (result '()))
                   (if (= remaining 0)
                       (reverse result)
                       (loop (cdr rest)
                             (- remaining 1)
                             (cons (car rest) result))))))
           (let loop ((env-rest env-params) (capture-rest captures))
             (if (or (null? env-rest) (null? capture-rest))
                 'done
                 (begin
                   (add-flow! var-flow
                              (car env-rest)
                              (analyze-expr (car capture-rest) current-proc))
                   (loop (cdr env-rest) (cdr capture-rest)))))
           (list proc-name)))
        ((closure-call)
         (let* ((proc-set (analyze-expr (cadr expr) current-proc))
                (arg-sets (map (lambda (arg)
                                 (analyze-expr arg current-proc))
                               (cddr expr))))
           (for-each
            (lambda (proc-name)
              (let* ((meta (hash-table-ref/default procedures proc-name #f))
                     (capture-count (car meta))
                     (params (cadr meta))
                     (actual-params (list-tail params capture-count)))
                (let loop ((param-rest actual-params) (arg-rest arg-sets))
                  (if (or (null? param-rest) (null? arg-rest))
                      'done
                      (begin
                        (add-flow! var-flow (car param-rest) (car arg-rest))
                        (loop (cdr param-rest) (cdr arg-rest)))))))
            proc-set)
           (let loop ((rest proc-set) (result '()))
             (if (null? rest)
                 result
                 (loop (cdr rest)
                       (set-union result
                                  (flow-ref proc-results (car rest))))))))
        ((self-tail-call)
         (let ((meta (and current-proc (hash-table-ref/default procedures current-proc #f))))
           (if (not meta)
               '()
               (let* ((capture-count (car meta))
                      (params (cadr meta))
                      (actual-params (list-tail params capture-count))
                      (actual-arg-sets
                       (map (lambda (arg)
                              (analyze-expr arg current-proc))
                            (list-tail (cdr expr) capture-count))))
                 (let loop ((param-rest actual-params) (arg-rest actual-arg-sets))
                   (if (or (null? param-rest) (null? arg-rest))
                       'done
                       (begin
                         (add-flow! var-flow (car param-rest) (car arg-rest))
                         (loop (cdr param-rest) (cdr arg-rest)))))
                 (flow-ref proc-results current-proc)))))
        ((group-tail-call)
         (begin
           (for-each (lambda (arg)
                       (analyze-expr arg current-proc))
                     (cddr expr))
           '()))
        ((group-closures)
         (begin
           (for-each (lambda (capture-spec)
                       (analyze-expr (cadr capture-spec) current-proc))
                     (caddr expr))
           '()))
        ((box)
         (begin
           (analyze-expr (cadr expr) current-proc)
           '()))
        ((unbox)
         (let ((key (box-key (cadr expr))))
           (analyze-expr (cadr expr) current-proc)
           (if key
               (flow-ref box-flow key)
               '())))
        ((set-box!)
         (let ((value-set (analyze-expr (caddr expr) current-proc))
               (key (box-key (cadr expr))))
           (analyze-expr (cadr expr) current-proc)
           (add-flow! box-flow key value-set)
           value-set))
        ((set-global!)
         (let ((value-set (analyze-expr (caddr expr) current-proc)))
           (add-flow! global-flow (cadr expr) value-set)
           value-set))
        (else
         (error "Unknown expression in 0CFA" (car expr)))))
     (else
      (error "Invalid expression in 0CFA" expr))))

  (let loop ()
    (set! changed #f)
    (analyze-expr expr #f)
    (for-each
     (lambda (proc-name)
       (let* ((meta (hash-table-ref/default procedures proc-name #f))
              (body (caddr meta))
              (result-set (analyze-expr body proc-name)))
         (add-flow! proc-results proc-name result-set)))
     (table-keys procedures))
    (if changed
        (loop)
        (list procedures var-flow box-flow global-flow proc-results))))

(define (rewrite-known-calls expr analysis)
  (let ((procedures (car analysis))
        (var-flow (cadr analysis))
        (box-flow (caddr analysis))
        (global-flow (cadddr analysis)))
    (define (flow-ref table key)
      (let ((value (hash-table-ref/default table key #f)))
        (if value value '())))

    (define (repr-name expr)
      (cond
       ((symbol? expr) expr)
       ((and (pair? expr) (memq (car expr) '(local closure))) (cadr expr))
       (else #f)))

    (define (box-key expr)
      (repr-name expr))

    (define (closure-set expr)
      (cond
       ((symbol? expr) (flow-ref var-flow expr))
       ((literal-expr? expr) '())
       ((pair? expr)
        (case (car expr)
          ((local closure)
           (flow-ref var-flow (cadr expr)))
          ((global)
           (flow-ref global-flow (cadr expr)))
          ((unbox)
           (let ((key (box-key (cadr expr))))
             (if key
                 (flow-ref box-flow key)
                 '())))
          ((make-closure)
           (list (cadr expr)))
          ((let)
           (closure-set (body->expr (cddr expr))))
          ((begin)
           (if (null? (cdr expr))
               '()
               (closure-set (car (reverse (cdr expr))))))
          ((if)
           (set-union (closure-set (caddr expr))
                      (closure-set (cadddr expr))))
          (else '())))
       (else '())))

    (define (rewrite expr)
      (cond
       ((or (symbol? expr) (literal-expr? expr)) expr)
       ((pair? expr)
        (case (car expr)
          ((begin)
           `(begin ,@(map rewrite (cdr expr))))
          ((primop)
           `(primop ,(cadr expr) ,@(map rewrite (cddr expr))))
          ((if)
           `(if ,(rewrite (cadr expr))
                ,(rewrite (caddr expr))
                ,(rewrite (cadddr expr))))
          ((let)
           `(let ,(map (lambda (binding)
                         (list (car binding)
                               (rewrite (cadr binding))))
                       (cadr expr))
              ,@(map rewrite (cddr expr))))
          ((lambda)
           `(lambda ,(cadr expr) ,@(map rewrite (cddr expr))))
          ((make-closure)
           `(make-closure ,(cadr expr)
                          ,(rewrite (caddr expr))
                          ,@(map rewrite (cdddr expr))))
          ((closure-call)
           (let* ((rator (rewrite (cadr expr)))
                  (args (map rewrite (cddr expr)))
                  (targets (closure-set rator)))
             (if (and (= (length targets) 1)
                      (hash-table-ref/default procedures (car targets) #f))
                 (let* ((proc-name (car targets))
                        (meta (hash-table-ref/default procedures proc-name #f))
                        (capture-count (car meta)))
                   `(known-call ,proc-name ,capture-count ,rator ,@args))
                 `(closure-call ,rator ,@args))))
          ((known-call)
           `(known-call ,(cadr expr)
                        ,(caddr expr)
                        ,(rewrite (cadddr expr))
                        ,@(map rewrite (cddddr expr))))
          ((self-tail-call)
           `(self-tail-call ,@(map rewrite (cdr expr))))
          ((group-tail-call)
           `(group-tail-call ,(cadr expr) ,@(map rewrite (cddr expr))))
          ((group-closures)
           `(group-closures
             ,(map (lambda (member)
                     (list (car member)
                           (cadr member)
                           (caddr member)
                           (rewrite (cadddr member))))
                   (cadr expr))
             ,(map (lambda (capture-spec)
                     (list (car capture-spec)
                           (rewrite (cadr capture-spec))))
                   (caddr expr))))
          ((cons set-box! make-vector vector-ref vector-set!)
           `(,(car expr) ,(rewrite (cadr expr)) ,(rewrite (caddr expr))))
          ((set-global!)
           `(set-global! ,(cadr expr) ,(rewrite (caddr expr))))
          ((box unbox car cdr pair? null? vector-length vector? local closure global)
           `(,(car expr) ,(rewrite (cadr expr))))
          (else
           (error "Unknown expression in known-call rewrite" (car expr)))))
       (else
        (error "Invalid expression in known-call rewrite" expr))))

    (rewrite expr)))

)) ; end define-library
