(define-library (hop pass closure)
  ;;; Pass 3: Closure Conversion
  ;;; Turns lambdas into explicit closure values with captured environments.
  (export free-vars
          closure-convert)
  (import (scheme base)
          (scheme cxr)
          (hop utils))
  (begin

(define (free-vars expr bound)
  (define (collect expr bound)
    (cond
     ((symbol? expr)
      (if (memq expr bound) '() (list expr)))

     ((literal-expr? expr) '())

     ((pair? expr)
      (case (car expr)
        ((begin)
         (append-map (lambda (e) (collect e bound)) (cdr expr)))

        ((primop)
         (append-map (lambda (e) (collect e bound)) (cddr expr)))

        ((if)
         (append (collect (cadr expr) bound)
                 (collect (caddr expr) bound)
                 (collect (cadddr expr) bound)))

        ((let)
         (let* ((binding (caadr expr))
                (var (car binding))
                (val (cadr binding))
                (body (body->expr (cddr expr))))
           (append (collect val bound)
                   (collect body (cons var bound)))))

        ((lambda)
         (let* ((params (cadr expr))
                (body (body->expr (cddr expr))))
           (collect body (append params bound))))

        ((app)
         (append-map (lambda (e) (collect e bound)) (cdr expr)))

        ((self-tail-call)
         (append-map (lambda (e) (collect e bound)) (cdr expr)))

        ((group-tail-call)
         (append-map (lambda (e) (collect e bound)) (cddr expr)))

        ((box unbox)
         (collect (cadr expr) bound))

        ((global)
         '())

        ((set-global!)
         (collect (caddr expr) bound))

        ((set-box!)
         (append (collect (cadr expr) bound)
                 (collect (caddr expr) bound)))

        (else (error "Unknown expression in free-vars" (car expr)))))

     (else '())))

  (dedupe-symbols (collect expr bound)))

(define (closure-convert expr)
  (define (any predicate lst)
    (cond
     ((null? lst) #f)
     ((predicate (car lst)) #t)
     (else (any predicate (cdr lst)))))

  (define (make-env-vars prefix count)
    (let loop ((i 0) (result '()))
      (if (= i count)
          (reverse result)
          (loop (+ i 1)
                (cons (string->symbol
                       (string-append prefix (number->string i)))
                      result)))))

  (define (local-repr-name repr)
    (and (pair? repr)
         (eq? (car repr) 'local)
         (pair? (cdr repr))
         (symbol? (cadr repr))
         (cadr repr)))

  (define (lookup-repr name env)
    (let ((binding (assoc name env)))
      (if binding
          (cadr binding)
          name)))

  (define (collect-group-tail-targets expr)
    (cond
     ((or (symbol? expr) (literal-expr? expr)) '())
     ((pair? expr)
      (case (car expr)
        ((group-tail-call)
         (cons (cadr expr)
               (append-map collect-group-tail-targets (cddr expr))))
        ((begin app set-box!)
         (append-map collect-group-tail-targets (cdr expr)))
        ((primop)
         (append-map collect-group-tail-targets (cddr expr)))
        ((if)
         (append (collect-group-tail-targets (cadr expr))
                 (collect-group-tail-targets (caddr expr))
                 (collect-group-tail-targets (cadddr expr))))
        ((let)
         (append (collect-group-tail-targets (cadr (caadr expr)))
                 (append-map collect-group-tail-targets (cddr expr))))
        ((lambda)
         (collect-group-tail-targets (body->expr (cddr expr))))
        ((box unbox)
         (collect-group-tail-targets (cadr expr)))
        ((global)
         '())
        ((set-global!)
         (collect-group-tail-targets (caddr expr)))
        (else '())))
     (else '())))

  (define (mentions-box-var? expr box-vars)
    (cond
     ((symbol? expr) (memq expr box-vars))
     ((literal-expr? expr) #f)
     ((pair? expr)
      (case (car expr)
        ((begin app primop set-box!)
         (any (lambda (e) (mentions-box-var? e box-vars)) (cdr expr)))
        ((if)
         (or (mentions-box-var? (cadr expr) box-vars)
             (mentions-box-var? (caddr expr) box-vars)
             (mentions-box-var? (cadddr expr) box-vars)))
        ((let)
         (or (mentions-box-var? (cadr (caadr expr)) box-vars)
             (any (lambda (e) (mentions-box-var? e box-vars)) (cddr expr))))
        ((lambda)
         (mentions-box-var? (body->expr (cddr expr)) box-vars))
        ((box unbox)
         (mentions-box-var? (cadr expr) box-vars))
        ((global)
         #f)
        ((set-global!)
         (mentions-box-var? (caddr expr) box-vars))
        (else #f)))
     (else #f)))

  (define (safe-group-body? expr box-vars)
    (cond
     ((symbol? expr) (not (memq expr box-vars)))
     ((literal-expr? expr) #t)
     ((pair? expr)
      (case (car expr)
        ((begin)
         (all (lambda (e) (safe-group-body? e box-vars)) (cdr expr)))
        ((primop)
         (all (lambda (e) (safe-group-body? e box-vars)) (cddr expr)))
        ((if)
         (and (safe-group-body? (cadr expr) box-vars)
              (safe-group-body? (caddr expr) box-vars)
              (safe-group-body? (cadddr expr) box-vars)))
        ((let)
         (and (safe-group-body? (cadr (caadr expr)) box-vars)
              (all (lambda (e) (safe-group-body? e box-vars)) (cddr expr))))
        ((lambda)
         (not (mentions-box-var? (body->expr (cddr expr)) box-vars)))
        ((app)
         (let ((rator (cadr expr))
               (args (cddr expr)))
           (if (and (pair? rator)
                    (eq? (car rator) 'unbox)
                    (symbol? (cadr rator))
                    (memq (cadr rator) box-vars))
               (all (lambda (arg) (safe-group-body? arg box-vars)) args)
               (and (safe-group-body? rator box-vars)
                    (all (lambda (arg) (safe-group-body? arg box-vars)) args)))))
        ((cons make-vector vector-length vector-ref vector-set! vector?)
         (error "vector or list op in safe-group-body?: should have been canonicalized" expr))
        ((box)
         (safe-group-body? (cadr expr) box-vars))
        ((unbox)
         (let ((target (cadr expr)))
           (if (and (symbol? target) (memq target box-vars))
               #f
               (safe-group-body? target box-vars))))
        ((set-box!)
         (and (not (and (symbol? (cadr expr)) (memq (cadr expr) box-vars)))
              (safe-group-body? (cadr expr) box-vars)
              (safe-group-body? (caddr expr) box-vars)))
        ((global)
         #t)
        ((set-global!)
         (safe-group-body? (caddr expr) box-vars))
        (else #f)))
     (else #f)))

  (define (extract-group-prefix exprs env)
    (define (links-other-member? member names)
      (let ((name (cadr member))
            (targets (collect-group-tail-targets (cadddr member))))
        (let loop ((rest-targets targets))
          (cond
           ((null? rest-targets) #f)
           ((and (memq (car rest-targets) names)
                 (not (eq? (car rest-targets) name)))
            #t)
           (else
            (loop (cdr rest-targets)))))))

    (define (finish members rest)
      (let ((names (map cadr members))
            (box-vars (map cadr members)))
        (if (and (> (length members) 1)
                 (safe-group-body? (body->expr rest) box-vars)
                 (any (lambda (member)
                        (links-other-member? member names))
                      members))
            (cons members rest)
            #f)))

    (let loop ((rest exprs) (members '()))
      (if (null? rest)
          (finish members '())
          (let ((expr (car rest)))
            (if (and (pair? expr)
                     (eq? (car expr) 'set-box!)
                     (symbol? (cadr expr))
                     (pair? (caddr expr))
                     (eq? (car (caddr expr)) 'lambda))
                (let* ((box-name (cadr expr))
                       (box-repr (lookup-repr box-name env))
                       (local-box (local-repr-name box-repr))
                       (lambda-expr (caddr expr)))
                  (if local-box
                      (loop (cdr rest)
                            (append members
                                    (list (list local-box
                                                box-name
                                                (cadr lambda-expr)
                                                (body->expr (cddr lambda-expr))))))
                      (finish members rest)))
                (finish members rest))))))

  (define (convert-group-prefix exprs env self-tail-prefix)
    (let ((prefix (extract-group-prefix exprs env)))
      (and prefix
           (let* ((members (car prefix))
                  (remaining (cdr prefix))
                  (member-names (map cadr members))
                  (shared-captures
                   (dedupe-symbols
                    (append-map
                     (lambda (member)
                       (free-vars (cadddr member)
                                  (append (caddr member) member-names)))
                     members)))
                  (capture-params
                   (make-env-vars "group.env." (length shared-captures)))
                  (shared-capture-map
                   (map (lambda (fv cp) (list fv cp))
                        shared-captures capture-params))
                  (per-member-cap-bindings
                   (map (lambda (member)
                          (let* ((member-fvs (free-vars (cadddr member)
                                                        (append (caddr member) member-names)))
                                 (bindings
                                  (filter (lambda (pair)
                                            (memq (car pair) member-fvs))
                                          shared-capture-map)))
                            (map (lambda (pair)
                                   (list (car pair) `(local ,(cadr pair))))
                                 bindings)))
                        members))
                  (capture-values
                   (map (lambda (fv capture-param)
                          (list capture-param (lookup-repr fv env)))
                        shared-captures
                        capture-params))
                  (converted-members
                   (map (lambda (member cap-bindings)
                          (let* ((box-var (car member))
                                 (member-name (cadr member))
                                 (params (caddr member))
                                 (body (cadddr member))
                                 (param-bindings
                                  (map (lambda (param)
                                         (list param `(local ,param)))
                                       params))
                                 (capture-names (map (lambda (binding)
                                                       (cadr (cadr binding)))
                                                     cap-bindings))
                                 (body-env (append param-bindings cap-bindings env)))
                            (list box-var member-name params
                                  (convert body body-env '())
                                  capture-names)))
                        members per-member-cap-bindings)))
             (cons (cons `(group-closures ,converted-members ,capture-values)
                         (map (lambda (e) (convert e env self-tail-prefix)) remaining))
                   #t)))))

  (define (convert-sequence exprs env self-tail-prefix)
    (let ((group-result (convert-group-prefix exprs env self-tail-prefix)))
      (if group-result
          (car group-result)
          (map (lambda (e) (convert e env self-tail-prefix)) exprs))))

  (define (convert expr env self-tail-prefix)
    (cond
     ((symbol? expr)
      (let ((binding (assoc expr env)))
        (if binding
            (cadr binding)
            expr)))

     ((literal-expr? expr)
      expr)
     ((pair? expr)
      (case (car expr)
        ((begin)
         `(begin ,@(convert-sequence (cdr expr) env self-tail-prefix)))
        ((primop)
         `(primop ,(cadr expr)
                  ,@(map (lambda (e) (convert e env self-tail-prefix)) (cddr expr))))
        ((if)
         `(if ,(convert (cadr expr) env self-tail-prefix)
              ,(convert (caddr expr) env self-tail-prefix)
              ,(convert (cadddr expr) env self-tail-prefix)))
        ((let)
         (let* ((bindings (map (lambda (binding)
                                 (list (car binding)
                                       (convert (cadr binding) env self-tail-prefix)))
                               (cadr expr)))
                (new-vars (map car bindings))
                (new-env (append (map (lambda (var)
                                        (list var `(local ,var)))
                                      new-vars)
                                 env))
                (body (body->expr (cddr expr)))
                (body-converted (convert body new-env self-tail-prefix)))
           `(let ,bindings ,body-converted)))
        ((lambda)
         (let* ((params (cadr expr))
                (body (body->expr (cddr expr)))
                (fvs (free-vars body params))
                (env-vars (make-env-vars "env." (length fvs)))
                (param-bindings (map (lambda (p) (list p `(local ,p))) params))
                (env-bindings (map (lambda (fv env-var)
                                     (list fv `(closure ,env-var)))
                                   fvs env-vars))
                (new-env (append param-bindings env-bindings env))
                (self-tail-env (map (lambda (env-var) `(local ,env-var)) env-vars))
                (body-converted (convert body new-env self-tail-env)))
           `(make-closure
             (lambda ,(append env-vars params) ,body-converted)
             ,@(map (lambda (fv)
                      (let ((binding (assoc fv env)))
                        (if binding
                            (cadr binding)
                            fv)))
                    fvs))))
        ((app)
         (let ((rator (cadr expr))
               (rands (cddr expr)))
           `(closure-call ,(convert rator env self-tail-prefix)
                          ,@(map (lambda (e) (convert e env self-tail-prefix)) rands))))
        ((cons)
         (error "cons in closure-convert: should have been canonicalized" expr))
        ((self-tail-call)
         `(self-tail-call
           ,@self-tail-prefix
           ,@(map (lambda (e) (convert e env self-tail-prefix)) (cdr expr))))
        ((group-tail-call)
         `(group-tail-call
           ,(cadr expr)
           ,@(map (lambda (e) (convert e env self-tail-prefix)) (cddr expr))))
        ((group-closures global)
         expr)
        ((box)
         `(box ,(convert (cadr expr) env self-tail-prefix)))
        ((unbox)
         `(unbox ,(convert (cadr expr) env self-tail-prefix)))
        ((car)
         (error "car in closure-convert: should have been canonicalized" expr))
        ((cdr)
         (error "cdr in closure-convert: should have been canonicalized" expr))
        ((pair?)
         (error "pair? in closure-convert: should have been canonicalized" expr))
        ((null?)
         (error "null? in closure-convert: should have been canonicalized" expr))
        ((make-vector)
         (error "make-vector in closure-convert: should have been canonicalized" expr))
        ((vector-length)
         (error "vector-length in closure-convert: should have been canonicalized" expr))
        ((vector-ref)
         (error "vector-ref in closure-convert: should have been canonicalized" expr))
        ((vector-set!)
         (error "vector-set! in closure-convert: should have been canonicalized" expr))
        ((set-box!)
         `(set-box! ,(convert (cadr expr) env self-tail-prefix)
                    ,(convert (caddr expr) env self-tail-prefix)))
        ((set-global!)
         `(set-global! ,(cadr expr)
                       ,(convert (caddr expr) env self-tail-prefix)))
        (else
         (error "Unknown expression in closure-convert" (car expr)))))

     (else (error "Invalid expression in closure-convert" expr))))

  (convert expr '() '()))

)) ; end define-library
