; symbolic differentiation, simplification and evaluation of tagged trees
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (num? e) (not (pair? e)))
(define (make-sum a b)
  (cond ((and (num? a) (eq? a 0)) b)
        ((and (num? b) (eq? b 0)) a)
        ((and (number? a) (number? b)) (+ a b))
        (else `(+ ,a ,b))))
(define (number? x) (not (or (pair? x) (symbol? x) (null? x))))
(define (make-product a b)
  (cond ((or (eq? a 0) (eq? b 0)) 0)
        ((eq? a 1) b)
        ((eq? b 1) a)
        ((and (number? a) (number? b)) (* a b))
        (else `(* ,a ,b))))
(define (deriv e v)
  (cond ((number? e) 0)
        ((symbol? e) (if (eq? e v) 1 0))
        ((eq? (car e) '+) (make-sum (deriv (cadr e) v) (deriv (caddr e) v)))
        ((eq? (car e) '*)
         (make-sum (make-product (cadr e) (deriv (caddr e) v))
                   (make-product (deriv (cadr e) v) (caddr e))))
        (else 0)))
(define (lookup v env)
  (cond ((null? env) 0)
        ((eq? (car (car env)) v) (cdr (car env)))
        (else (lookup v (cdr env)))))
(define (evaluate e env)
  (cond ((number? e) e)
        ((symbol? e) (lookup e env))
        ((eq? (car e) '+) (+ (evaluate (cadr e) env) (evaluate (caddr e) env)))
        (else (* (evaluate (cadr e) env) (evaluate (caddr e) env)))))
(define env `((x . 3) (y . 5)))
(define poly '(+ (* x (* x y)) (+ (* 3 x) (* y 7))))
(+ (evaluate (deriv poly 'x) env) (evaluate (deriv poly 'y) env))
