; an interpreter for a small expression language; programs are quoted data
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (cadddr x) (car (cdr (cdr (cdr x)))))
(define (lookup v env)
  (cond ((null? env) 0)
        ((eq? (car (car env)) v) (cdr (car env)))
        (else (lookup v (cdr env)))))
(define (interp e env)
  (let ((tag (car e)))
    (cond ((eq? tag 'num) (cadr e))
          ((eq? tag 'var) (lookup (cadr e) env))
          ((eq? tag 'add) (+ (interp (cadr e) env) (interp (caddr e) env)))
          ((eq? tag 'mul) (* (interp (cadr e) env) (interp (caddr e) env)))
          ((eq? tag 'sub) (- (interp (cadr e) env) (interp (caddr e) env)))
          ((eq? tag 'if0)
           (if (= (interp (cadr e) env) 0)
               (interp (caddr e) env)
               (interp (cadddr e) env)))
          ((eq? tag 'let)
           (interp (cadddr e)
                   (cons (cons (cadr e) (interp (caddr e) env)) env)))
          (else 0))))
(define prog1 '(let a (num 6) (let b (mul (var a) (num 7)) (add (var a) (var b)))))
(define prog2 '(if0 (sub (num 3) (num 3)) (num 10) (num 20)))
(define prog3 '(let x (num 5) (if0 (var x) (num 1) (mul (var x) (add (var x) (num 2))))))
(+ (interp prog1 '()) (+ (interp prog2 '()) (interp prog3 '())))
