; list utilities, as a program would define them (no list library exists)
(define (reverse-onto l acc)
  (if (null? l) acc (reverse-onto (cdr l) (cons (car l) acc))))
(define (reverse l) (reverse-onto l '()))
(define (append a b)
  (if (null? a) b (cons (car a) (append (cdr a) b))))
(define (length l) (if (null? l) 0 (+ 1 (length (cdr l)))))
(define (map1 f l) (if (null? l) '() (cons (f (car l)) (map1 f (cdr l)))))
(define (filter keep? l)
  (cond ((null? l) '())
        ((keep? (car l)) (cons (car l) (filter keep? (cdr l))))
        (else (filter keep? (cdr l)))))
(define (sum l) (if (null? l) 0 (+ (car l) (sum (cdr l)))))
(define (range lo hi) (if (< lo hi) (cons lo (range (+ lo 1) hi)) '()))
(define (small? x) (< x 5))
(define (add1 x) (+ x 1))
(define xs (range 0 10))
(+ (sum (map1 add1 (filter small? (append xs (reverse xs)))))
   (length (append '(1 2 3) '(4 5))))
