; pattern matching: ?x binds, other symbols and numbers must be equal
(define (var? p) (eq? p '?))
(define (match pat datum bindings)
  (cond ((eq? bindings 'fail) 'fail)
        ((null? pat) (if (null? datum) bindings 'fail))
        ((not (pair? pat)) (if (eq? pat datum) bindings 'fail))
        ((eq? (car pat) '?)
         (cons (cons (car (cdr pat)) datum) bindings))
        ((pair? datum)
         (match (cdr pat) (cdr datum) (match (car pat) (car datum) bindings)))
        (else 'fail)))
(define (count-bindings b) (if (pair? b) (+ 1 (count-bindings (cdr b))) 0))
(define (try pat datum)
  (let ((r (match pat datum '())))
    (if (eq? r 'fail) 0 (+ 10 (count-bindings r)))))
(+ (try '(1 (? a) 3) '(1 2 3))
   (+ (try '((? a) (? b) (? c)) '(1 2 3))
      (+ (try '(1 (? a) 4) '(1 2 3))
         (try '(x (y (? z))) '(x (y 9))))))
