; expression trees built with quasiquote and folded by a recursive function
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (mk-add a b) `(add ,a ,b))
(define (mk-mul a b) `(mul ,a ,b))
(define (mk-neg a) `(neg ,a))
(define (build n)
  (if (= n 0)
      `(num ,n)
      (mk-add (mk-mul `(num ,n) (build (- n 1)))
              (mk-neg (build (- n 1))))))
(define (evaluate e)
  (let ((k (car e)))
    (cond ((eq? k 'num) (cadr e))
          ((eq? k 'add) (+ (evaluate (cadr e)) (evaluate (caddr e))))
          ((eq? k 'mul) (* (evaluate (cadr e)) (evaluate (caddr e))))
          (else (- 0 (evaluate (cadr e)))))))
(define (size e)
  (let ((k (car e)))
    (cond ((eq? k 'num) 1)
          ((eq? k 'neg) (+ 1 (size (cadr e))))
          (else (+ 1 (+ (size (cadr e)) (size (caddr e))))))))
(let ((t (build 6)))
  (+ (evaluate t) (size t)))
