; messages built with quasiquote and dispatched on a tag
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (cadddr x) (car (cdr (cdr (cdr x)))))
(define (msg-kind m) (car m))
(define (msg-id m) (cadr m))
(define (msg-body m) (caddr m))
(define (make-ping id) `(ping ,id (body 0 0)))
(define (make-move id x y) `(move ,id (body ,x ,y)))
(define (make-stop id) `(stop ,id (body 0 0)))
(define (body-x b) (cadr b))
(define (body-y b) (caddr b))
(define (handle m acc)
  (let ((k (msg-kind m)) (b (msg-body m)))
    (cond ((eq? k 'ping) (+ acc 1))
          ((eq? k 'move) (+ acc (+ (body-x b) (body-y b))))
          (else (- acc (msg-id m))))))
(define (session n acc)
  (if (= n 0)
      acc
      (session (- n 1)
               (handle (make-stop n)
                       (handle (make-move n n 2)
                               (handle (make-ping n) acc))))))
(session 200 0)
