; a loop carrying a quasiquoted state record that is read and rebuilt each step
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (cadddr x) (car (cdr (cdr (cdr x)))))
(define (state-count s) (cadr s))
(define (state-total s) (caddr s))
(define (state-mode s) (cadddr s))
(define (step s i)
  (let ((m (state-mode s)))
    (if (eq? m 'up)
        `(state ,(+ (state-count s) 1) ,(+ (state-total s) i) down)
        `(state ,(+ (state-count s) 1) ,(- (state-total s) 1) up))))
(define (run n)
  (letrec ((loop (lambda (i s)
                   (if (= i n)
                       s
                       (loop (+ i 1) (step s i))))))
    (loop 0 `(state 0 0 up))))
(let ((final (run 200)))
  (+ (state-count final) (state-total final)))
