; instantiating code templates with quasiquote, then walking the result
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (let-form v e body) `(let ((,v ,e)) ,body))
(define (if-form c a b) `(if ,c ,a ,b))
(define (gen n)
  (if (= n 0)
      `(var x)
      (let-form n `(call f ,n) (if-form `(var ,n) (gen (- n 1)) `(const ,n)))))
(define (count e)
  (cond ((null? e) 0)
        ((pair? e) (+ (count (car e)) (count (cdr e))))
        (else 1)))
(+ (count (gen 12)) (count (gen 3)))
