; a stack machine whose program is a quasiquoted instruction list
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (program k) `((push ,k) (push 3) add (push 2) mul (dup) add halt))
(define (run code stack)
  (let ((ins (car code)))
    (cond ((eq? ins 'halt) (car stack))
          ((eq? ins 'add) (run (cdr code) (cons (+ (car stack) (cadr stack)) (cdr (cdr stack)))))
          ((eq? ins 'mul) (run (cdr code) (cons (* (car stack) (cadr stack)) (cdr (cdr stack)))))
          ((eq? (car ins) 'push) (run (cdr code) (cons (cadr ins) stack)))
          (else (run (cdr code) (cons (car stack) stack))))))
(define (many n acc)
  (if (= n 0) acc (many (- n 1) (+ acc (run (program n) '())))))
(many 100 0)
