; merge sort on lists of integers
(define (split l)
  (if (or (null? l) (null? (cdr l)))
      (cons l '())
      (let ((rest (split (cdr (cdr l)))))
        (cons (cons (car l) (car rest))
              (cons (car (cdr l)) (cdr rest))))))
(define (merge a b)
  (cond ((null? a) b)
        ((null? b) a)
        ((< (car a) (car b)) (cons (car a) (merge (cdr a) b)))
        (else (cons (car b) (merge a (cdr b))))))
(define (sort l)
  (if (or (null? l) (null? (cdr l)))
      l
      (let ((halves (split l)))
        (merge (sort (car halves)) (sort (cdr halves))))))
(define (weighted l i) (if (null? l) 0 (+ (* i (car l)) (weighted (cdr l) (+ i 1)))))
(weighted (sort '(5 3 9 1 7 2 8 4 6 0)) 1)
