; tagged records built with quasiquote and read back through accessors
(define (cadr x) (car (cdr x)))
(define (caddr x) (car (cdr (cdr x))))
(define (cadddr x) (car (cdr (cdr (cdr x)))))
(define (make-node kind payload) `(node ,kind ,payload 0))
(define (node-kind n) (cadr n))
(define (node-payload n) (caddr n))
(define (header v) `(header ,v payload))
(define (header-value h) (cadr h))
(define (score n)
  (let ((k (node-kind n)))
    (cond ((eq? k 'leaf) (node-payload n))
          ((eq? k 'pair) (+ (score (car (node-payload n)))
                            (score (cdr (node-payload n)))))
          (else 0))))
(define (tree depth)
  (if (= depth 0)
      (make-node 'leaf 1)
      (make-node 'pair (cons (tree (- depth 1)) (tree (- depth 1))))))
(define (describe v) (cadr (cdr (header v))))
(+ (score (tree 5))
   (+ (header-value (header 7))
      (if (eq? (describe 1) 'payload) 100 0)))
