;;; Regenerates hop/includes.scm from the (define-library ...) forms under
;;; hop/. Each hop/**/*.sld file declares its own dependencies via its
;;; (import ...) clause, so this script reads that clause back out of every
;;; file, topologically sorts the local (hop ...) libraries by it, and
;;; writes one (include "...") form per file in that order. Only Chicken needs
;;; this: Guile finds each library as hop/<name>.sld on its load path (-L .)
;;; and compiles it as its own module.
;;;
;;; Usage (any R7RS host: csi -s, or guile):
;;;   <scheme> tools/gen-includes.scm <file.sld>... > hop/includes.scm
;;; The .sld list is passed in (the Makefile uses find) because directory
;;; listing is not part of R7RS.
;;;
;;; hop/includes.scm is generated -- never edit it by hand. Run `make
;;; hop/includes.scm` (or `build`/`test`/`repl`, which depend on it) to
;;; refresh it after adding, removing, or re-wiring a pass file.

(import (scheme base)
        (scheme read)
        (scheme write)
        (scheme file)
        (scheme process-context))

(define (keep pred lst)
  (cond
   ((null? lst) '())
   ((pred (car lst)) (cons (car lst) (keep pred (cdr lst))))
   (else (keep pred (cdr lst)))))

(define (drop-equal item lst)
  (keep (lambda (x) (not (equal? x item))) lst))

(define (read-library-form path)
  (call-with-input-file path read))

;; The body of (define-library <name> <decl> ...) is a list of decls such
;; as (export ...), (import ...), (include ...); pull out the operands of
;; every (import ...) decl.
(define (imported-libraries library-form)
  (apply append
         (map (lambda (decl)
                (if (and (pair? decl) (eq? (car decl) 'import))
                    (cdr decl)
                    '()))
              (cddr library-form))))

(define (local-library-name? name)
  (and (pair? name) (eq? (car name) 'hop)))

;; entries : list of (library-name path dep-name ...)
(define (build-entries paths)
  (map (lambda (path)
         (let* ((form (read-library-form path))
                (name (cadr form))
                (deps (keep local-library-name? (imported-libraries form))))
           (cons name (cons path deps))))
       paths))

(define (topological-sort entries)
  (let ((finished '())
        (in-progress '())
        (ordered '()))
    (define (entry-for name)
      (or (assoc name entries)
          (error "hop/includes.scm: no local library provides an import" name)))
    (define (visit name)
      (cond
       ((member name finished) 'done)
       ((member name in-progress)
        (error "hop/includes.scm: circular library dependency involving" name))
       (else
        (set! in-progress (cons name in-progress))
        (let ((entry (entry-for name)))
          (for-each visit (cddr entry))
          (set! ordered (cons (cadr entry) ordered)))
        (set! in-progress (drop-equal name in-progress))
        (set! finished (cons name finished)))))
    (for-each (lambda (entry) (visit (car entry))) entries)
    (reverse ordered)))

(define (sort-strings strings)
  (define (insert s sorted)
    (cond ((null? sorted) (list s))
          ((string<? s (car sorted)) (cons s sorted))
          (else (cons (car sorted) (insert s (cdr sorted))))))
  (let loop ((rest strings) (sorted '()))
    (if (null? rest) sorted (loop (cdr rest) (insert (car rest) sorted)))))

(define (main)
  (let* ((args (cdr (command-line)))
         ;; sorted so the output does not depend on the order find lists files
         (paths (sort-strings args))
         (entries (build-entries paths))
         (ordered-paths (topological-sort entries)))
    (display ";;; GENERATED by tools/gen-includes.scm -- do not edit by hand.\n")
    (display ";;; Run `make hop/includes.scm` (or build/test/repl) to refresh.\n\n")
    (for-each (lambda (path)
                (write `(include ,path))
                (newline))
              ordered-paths)))

(main)
