;;; Regenerates hop/includes.scm from the (define-library ...) forms under
;;; hop/. Each hop/**/*.sld file declares its own dependencies via its
;;; (import ...) clause, so this script reads that clause back out of every
;;; file, topologically sorts the local (hop ...) libraries by it, and
;;; writes one (include "...") form per file in that order.
;;;
;;; Usage: csi -s tools/gen-includes.scm <root-dir> > hop/includes.scm
;;;
;;; hop/includes.scm is generated -- never edit it by hand. Run `make
;;; hop/includes.scm` (or `build`/`test`/`repl`, which depend on it) to
;;; refresh it after adding, removing, or re-wiring a pass file.

(import (scheme base)
        (scheme read)
        (scheme write)
        (chicken file)
        (chicken pathname)
        (chicken process-context))

(define (find-sld-files root)
  (let loop ((dirs (list root)) (files '()))
    (if (null? dirs)
        (reverse files)
        (let scan ((entries (directory (car dirs)))
                   (subdirs '())
                   (files files))
          (if (null? entries)
              (loop (append (cdr dirs) (reverse subdirs)) files)
              (let ((path (make-pathname (car dirs) (car entries))))
                (cond
                 ((directory-exists? path)
                  (scan (cdr entries) (cons path subdirs) files))
                 ((equal? (pathname-extension path) "sld")
                  (scan (cdr entries) subdirs (cons path files)))
                 (else
                  (scan (cdr entries) subdirs files)))))))))

(define (keep pred lst)
  (cond
   ((null? lst) '())
   ((pred (car lst)) (cons (car lst) (keep pred (cdr lst))))
   (else (keep pred (cdr lst)))))

(define (drop-equal item lst)
  (keep (lambda (x) (not (equal? x item))) lst))

(define (read-library-form path)
  (call-with-input-file path read))

;; The body of (define-library <name> <decl> ...) is a list of decls such
;; as (export ...), (import ...), (include ...); pull out the operands of
;; every (import ...) decl.
(define (imported-libraries library-form)
  (apply append
         (map (lambda (decl)
                (if (and (pair? decl) (eq? (car decl) 'import))
                    (cdr decl)
                    '()))
              (cddr library-form))))

(define (local-library-name? name)
  (and (pair? name) (eq? (car name) 'hop)))

;; entries : list of (library-name path dep-name ...)
(define (build-entries paths)
  (map (lambda (path)
         (let* ((form (read-library-form path))
                (name (cadr form))
                (deps (keep local-library-name? (imported-libraries form))))
           (cons name (cons path deps))))
       paths))

(define (topological-sort entries)
  (let ((finished '())
        (in-progress '())
        (ordered '()))
    (define (entry-for name)
      (or (assoc name entries)
          (error "hop/includes.scm: no local library provides an import" name)))
    (define (visit name)
      (cond
       ((member name finished) 'done)
       ((member name in-progress)
        (error "hop/includes.scm: circular library dependency involving" name))
       (else
        (set! in-progress (cons name in-progress))
        (let ((entry (entry-for name)))
          (for-each visit (cddr entry))
          (set! ordered (cons (cadr entry) ordered)))
        (set! in-progress (drop-equal name in-progress))
        (set! finished (cons name finished)))))
    (for-each (lambda (entry) (visit (car entry))) entries)
    (reverse ordered)))

(define (main)
  (let* ((args (command-line-arguments))
         (root (if (null? args) "hop" (car args)))
         (paths (find-sld-files root))
         (entries (build-entries paths))
         (ordered-paths (topological-sort entries)))
    (display ";;; GENERATED by tools/gen-includes.scm -- do not edit by hand.\n")
    (display ";;; Run `make hop/includes.scm` (or build/test/repl) to refresh.\n\n")
    (for-each (lambda (path)
                (write `(include ,path))
                (newline))
              ordered-paths)))

(main)
